baseURL: http://example.org/
languageCode: en-us
title: Mcbomb
theme: docsy

contentDir: "content/en"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

security:
  exec:
    allow: ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']

language:
  en:
    languageName: English
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true
